proxy_cache off;
proxy_buffering off;

upstream django {
    ip_hash;
    server redace_django:8001;
}

upstream mapproxy_up {
    server redace_mapproxy:8080;
}

server {
    listen      80;
    server_name dockerhost;
    charset     utf-8;

    client_max_body_size 75M;

    location / {
        proxy_pass http://django;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /static/ {
        alias /collect_static/;
    }

    location /redace_map/ {
        proxy_pass http://172.16.238.3:80/;
    }

    location = /redace_map/crism {

        proxy_pass http://172.16.238.3:80/redace_map/?map=/maps/crism.map&$args;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        }

    location = /redace_map/themis {
        proxy_pass http://172.16.238.3:80/redace_map/?map=/maps/themis.map&$args;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /redace_terrain/ {
        proxy_pass http://172.16.238.4:8000/;
    }

    location /o/ {
        proxy_pass http://172.16.238.24:8001/o/;  # DjangoのOAuthエンドポイントに転送
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /userdata/ {
        proxy_pass http://172.16.238.24:8001/userdata/;  # Djangoのuserdataエンドポイントに転送
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location ^~ /wmts {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_pass http://redace_mapproxy:8080/service;
        proxy_read_timeout 600;

        add_header Access-Control-Allow-Origin * always;
        add_header Access-Control-Allow-Methods "GET, OPTIONS" always;
        add_header Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Accept" always;
    }

    location ^~ /service {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_pass http://172.16.238.7:8080;
        proxy_read_timeout 600;
    }

    location /collect_static/mars_dataset_tatsuya/ {
        alias /mars_dataset_tatsuya/;
        autoindex off;
        add_header Cache-Control "public, max-age=86400";
    }



    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    proxy_read_timeout 900;
}
