# Generated by Django 3.1 on 2024-12-31 04:36

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spectrums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=10)),
                ('obs_id', models.CharField(blank=True, max_length=50)),
                ('path', models.TextField()),
                ('image_path', models.TextField()),
                ('x_pixel', models.TextField()),
                ('y_pixel', models.TextField()),
                ('x_image_size', models.IntegerField()),
                ('y_image_size', models.IntegerField()),
                ('wavelength', models.TextField()),
                ('reflectance', models.TextField()),
                ('mineral_id', models.IntegerField(blank=True, null=True)),
                ('latitude', models.JSONField()),
                ('longitude', models.JSONField()),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField()),
                ('data_id', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
