# Generated by Django 3.1 on 2024-12-29 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map3d', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectrum',
            name='x_pixel',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='spectrum',
            name='y_pixel',
            field=models.JSONField(),
        ),
    ]
