# Generated by Django 3.1 on 2024-12-29 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map3d', '0002_auto_20241229_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectrum',
            name='coordinate',
            field=models.JSONField(default=list),
        ),
    ]
