# Generated by Django 3.1 on 2024-12-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map3d', '0003_spectrum_coordinate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectrum',
            name='coordinate',
            field=models.JSONField(),
        ),
    ]
