# Generated by Django 3.1 on 2024-12-29 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map3d', '0004_auto_20241229_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectrum',
            name='coordinate',
            field=models.TextField(),
        ),
    ]
