# Generated by Django 3.1 on 2024-12-29 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map3d', '0005_auto_20241229_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spectrum',
            name='coordinate',
        ),
    ]
