# Generated by Django 3.1 on 2024-12-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map3d', '0006_remove_spectrum_coordinate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectrum',
            name='x_pixel',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='spectrum',
            name='y_pixel',
            field=models.TextField(),
        ),
    ]
