# Generated by Django 3.1 on 2024-12-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map3d', '0007_auto_20241229_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectrum',
            name='latitude',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='spectrum',
            name='longitude',
            field=models.TextField(),
        ),
    ]
